-- Seed teams table
-- Leagues: PL (Premier League), LIGA (La Liga), BL1 (Bundesliga), SA (Serie A), FL1 (Ligue 1)

INSERT OR IGNORE INTO teams (id, name, short_name, league) VALUES
-- Premier League
('arsenal',        'Arsenal',                  'ARS', 'PL'),
('aston-villa',    'Aston Villa',              'AVL', 'PL'),
('bournemouth',    'Bournemouth',              'BOU', 'PL'),
('brentford',      'Brentford',                'BRE', 'PL'),
('brighton',       'Brighton & Hove Albion',   'BHA', 'PL'),
('chelsea',        'Chelsea',                  'CHE', 'PL'),
('crystal-palace', 'Crystal Palace',           'CRY', 'PL'),
('everton',        'Everton',                  'EVE', 'PL'),
('fulham',         'Fulham',                   'FUL', 'PL'),
('ipswich',        'Ipswich Town',             'IPS', 'PL'),
('leicester',      'Leicester City',           'LEI', 'PL'),
('liverpool',      'Liverpool',                'LIV', 'PL'),
('man-city',       'Manchester City',          'MCI', 'PL'),
('man-utd',        'Manchester United',        'MUN', 'PL'),
('newcastle',      'Newcastle United',         'NEW', 'PL'),
('nottm-forest',   'Nottingham Forest',        'NFO', 'PL'),
('southampton',    'Southampton',              'SOU', 'PL'),
('spurs',          'Tottenham Hotspur',        'TOT', 'PL'),
('west-ham',       'West Ham United',          'WHU', 'PL'),
('wolves',         'Wolverhampton Wanderers',  'WOL', 'PL'),

-- La Liga
('real-madrid',    'Real Madrid',              'RMA', 'LIGA'),
('barcelona',      'Barcelona',                'BAR', 'LIGA'),
('atletico',       'Atlético Madrid',          'ATM', 'LIGA'),
('athletic-bilbao','Athletic Club',            'ATH', 'LIGA'),
('villarreal',     'Villarreal',               'VIL', 'LIGA'),
('real-sociedad',  'Real Sociedad',            'RSO', 'LIGA'),
('sevilla',        'Sevilla',                  'SEV', 'LIGA'),
('betis',          'Real Betis',               'BET', 'LIGA'),
('valencia',       'Valencia',                 'VAL', 'LIGA'),
('osasuna',        'Osasuna',                  'OSA', 'LIGA'),
('getafe',         'Getafe',                   'GET', 'LIGA'),
('celta-vigo',     'Celta Vigo',               'CEL', 'LIGA'),
('rayo-vallecano', 'Rayo Vallecano',           'RAY', 'LIGA'),
('mallorca',       'Mallorca',                 'MAL', 'LIGA'),
('las-palmas',     'Las Palmas',               'LPA', 'LIGA'),
('girona',         'Girona',                   'GIR', 'LIGA'),
('alaves',         'Alavés',                   'ALA', 'LIGA'),
('espanyol',       'Espanyol',                 'ESP', 'LIGA'),
('leganes',        'Leganés',                  'LEG', 'LIGA'),
('valladolid',     'Valladolid',               'VLL', 'LIGA'),

-- Bundesliga
('bayern',         'Bayern Munich',            'BAY', 'BL1'),
('dortmund',       'Borussia Dortmund',        'BVB', 'BL1'),
('rb-leipzig',     'RB Leipzig',               'RBL', 'BL1'),
('leverkusen',     'Bayer Leverkusen',         'LEV', 'BL1'),
('frankfurt',      'Eintracht Frankfurt',      'SGE', 'BL1'),
('wolfsburg',      'Wolfsburg',                'WOB', 'BL1'),
('m-gladbach',     'Borussia Mönchengladbach', 'BMG', 'BL1'),
('union-berlin',   'Union Berlin',             'UBL', 'BL1'),
('hoffenheim',     'Hoffenheim',               'TSG', 'BL1'),
('freiburg',       'SC Freiburg',              'SCF', 'BL1'),
('augsburg',       'FC Augsburg',              'AUG', 'BL1'),
('werder',         'Werder Bremen',            'SVW', 'BL1'),
('stuttgart',      'VfB Stuttgart',            'VFB', 'BL1'),
('mainz',          'Mainz 05',                 'M05', 'BL1'),
('heidenheim',     'Heidenheim',               'HDH', 'BL1'),
('st-pauli',       'St. Pauli',                'STP', 'BL1'),
('kiel',           'Holstein Kiel',            'KIE', 'BL1'),
('bochum',         'VfL Bochum',               'BOC', 'BL1'),

-- Serie A
('inter',          'Inter Milan',              'INT', 'SA'),
('juventus',       'Juventus',                 'JUV', 'SA'),
('milan',          'AC Milan',                 'MIL', 'SA'),
('napoli',         'Napoli',                   'NAP', 'SA'),
('atalanta',       'Atalanta',                 'ATA', 'SA'),
('roma',           'AS Roma',                  'ROM', 'SA'),
('lazio',          'Lazio',                    'LAZ', 'SA'),
('fiorentina',     'Fiorentina',               'FIO', 'SA'),
('bologna',        'Bologna',                  'BOL', 'SA'),
('torino',         'Torino',                   'TOR', 'SA'),
('genoa',          'Genoa',                    'GEN', 'SA'),
('lecce',          'Lecce',                    'LEC', 'SA'),
('cagliari',       'Cagliari',                 'CAG', 'SA'),
('udinese',        'Udinese',                  'UDI', 'SA'),
('empoli',         'Empoli',                   'EMP', 'SA'),
('verona',         'Hellas Verona',            'VER', 'SA'),
('venezia',        'Venezia',                  'VEN', 'SA'),
('parma',          'Parma',                    'PAR', 'SA'),
('como',           'Como',                     'COM', 'SA'),
('monza',          'Monza',                    'MON', 'SA'),

-- Ligue 1
('psg',            'Paris Saint-Germain',      'PSG', 'FL1'),
('marseille',      'Marseille',                'OM',  'FL1'),
('monaco',         'Monaco',                   'MON', 'FL1'),
('lille',          'Lille',                    'LIL', 'FL1'),
('lyon',           'Lyon',                     'OL',  'FL1'),
('nice',           'Nice',                     'NIC', 'FL1'),
('lens',           'RC Lens',                  'RCL', 'FL1'),
('rennes',         'Rennes',                   'REN', 'FL1'),
('strasbourg',     'Strasbourg',               'STR', 'FL1'),
('nantes',         'Nantes',                   'NAN', 'FL1'),
('toulouse',       'Toulouse',                 'TOU', 'FL1'),
('reims',          'Reims',                    'REI', 'FL1'),
('brest',          'Brest',                    'BRE', 'FL1'),
('montpellier',    'Montpellier',              'MPL', 'FL1'),
('angers',         'Angers',                   'ANG', 'FL1'),
('le-havre',       'Le Havre',                 'HAV', 'FL1'),
('st-etienne',     'Saint-Étienne',            'ASE', 'FL1'),
('auxerre',        'Auxerre',                  'AUX', 'FL1');
