name = "gaff3r-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [{ name = "USER_STATE", class_name = "UserState" }]

[[migrations]]
tag = "v1"
new_classes = ["UserState"]

[[kv_namespaces]]
binding = "FPL_CACHE"
id = "d5fe3844a311424e9e6fb8765807e036"

[ai]
binding = "AI"
